AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    IDLSAM

    Sample SAM Template for IDLSAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Api:
        Auth:
            AddDefaultAuthorizerToCorsPreflight: false
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            AllowOrigin: "'*'"
            MaxAge: "'600'"
    Function:
        Timeout: 3

Resources:
    ScheduleFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: scheduler/
            Handler: app.lambda_handler
            Runtime: python3.11
            Architectures:
                - x86_64
            Events:
                Schedule:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /schedule
                        Method: post
            Timeout: 30
            MemorySize: 256

    SubscheduleFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: subscheduler/
            Handler: app.lambda_handler
            Runtime: python3.11
            Architectures:
                - x86_64
            Events:
                Schedule:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /subschedule
                        Method: post
            Timeout: 30
            MemorySize: 128

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: hello/
            Handler: app.lambda_handler
            Runtime: python3.11
            Architectures:
                - x86_64
            Events:
                Hello:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /hello
                        Method: get

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    ScheduleApi:
        Description: "API Gateway endpoint URL for Prod stage for Schedule function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/schedule/"
    SubscheduleApi:
        Description: "API Gateway endpoint URL for Prod stage for Subschedule function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subschedule/"
    ScheduleFunction:
        Description: "Schedule Lambda Function ARN"
        Value: !GetAtt ScheduleFunction.Arn
    SubscheduleFunction:
        Description: "Subschedule Lambda Function ARN"
        Value: !GetAtt SubscheduleFunction.Arn
    ScheduleFunctionIamRole:
        Description: "Implicit IAM Role created for Schedule function"
        Value: !GetAtt ScheduleFunctionRole.Arn
    SubscheduleFunctionIamRole:
        Description: "Implicit IAM Role created for Subschedule function"
        Value: !GetAtt SubscheduleFunctionRole.Arn
